name: Plankefest.no
favicon: null
layout_spectrum: 0.50668
typography_spectrum: 0.48491
title: Plankefest.no
description: 'plankemøbler, helt enkelt!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f7f8fa'
    - '#dcdcdc'
    - '#464b47'
    - '#c0bfbd'
    - '#989fa5'
  brandStrength: 0.875
  lightness: 0
  saturation: 0.8125
  rhythmicContrast: 0
purpose: []
