name: Plankefest.no
favicon: null
layout_spectrum: 0.52103
typography_spectrum: 0.5823308432009071
title: Plankefest.no
description: 'plankemøbler, helt enkelt!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#E3DCD3'
    - '#A6A6A8'
    - '#575D59'
    - '#7E695C'
  brandStrength: 0.1875
  lightness: 0.8125
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
